# Generated by Django 5.2.6 on 2025-12-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address_document',
            field=models.FileField(blank=True, help_text='Upload a document showing your address', null=True, upload_to='address_documents/'),
        ),
    ]
