# Generated by Django 5.2.6 on 2025-12-14 05:08

from django.db import migrations


def fix_phone_numbers(apps, schema_editor):
    Resident = apps.get_model('accounts', 'Resident')
    for resident in Resident.objects.all():
        if resident.phone_number:
            # Keep only digits
            digits_only = ''.join(filter(str.isdigit, resident.phone_number))
            # If more than 11 digits, keep only the last 11
            if len(digits_only) > 11:
                resident.phone_number = digits_only[-11:]
            # If exactly 11 digits, keep as is
            elif len(digits_only) == 11:
                resident.phone_number = digits_only
            # If less than 11 digits, set to None (blank)
            else:
                resident.phone_number = None
            resident.save()


def reverse_fix_phone_numbers(apps, schema_editor):
    # Nothing to reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_resident_phone_number'),
    ]

    operations = [
        migrations.RunPython(fix_phone_numbers, reverse_fix_phone_numbers),
    ]