# Generated by Django 5.2.6 on 2025-12-14 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')]),
        ),
    ]
