# Generated by Django 5.2.6 on 2025-12-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_enforce_11_digit_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address_document',
            field=models.URLField(blank=True, help_text='URL to the document showing your address', null=True),
        ),
    ]
