# Generated by Django 5.2.6 on 2025-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_resident_address_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangaystaff',
            name='barangay_name',
        ),
        migrations.AddField(
            model_name='barangaystaff',
            name='first_name',
            field=models.CharField(default='Staff', max_length=50),
        ),
        migrations.AddField(
            model_name='barangaystaff',
            name='last_name',
            field=models.CharField(default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='barangaystaff',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
