# Generated by Django 5.2.6 on 2025-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_barangaystaff_barangay_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]