# Generated by Django 5.2.6 on 2025-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation provided by staff', null=True),
        ),
    ]