# Generated by Django 5.2.6 on 2025-12-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for rescheduling provided by staff', null=True),
        ),
    ]
