# Generated by Django 5.2.6 on 2025-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reschedule_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the appointment was rescheduled', null=True),
        ),
    ]
