# Generated by Django 5.2.6 on 2025-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_rescheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
