# Generated by Django 5.2.7 on 2025-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='custom_purpose',
            field=models.CharField(blank=True, help_text="Custom purpose when 'Others' is selected", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(choices=[('employment', 'Employment'), ('business_permit', 'Business Permit'), ('government_benefits', 'Government Benefits'), ('loan_application', 'Loan Application'), ('travel', 'Travel'), ('education', 'Education'), ('others', 'Others (Please Specify)')], default='employment', max_length=50),
        ),
    ]
