# Generated by Django 5.2.7 on 2025-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_custom_purpose_alter_appointment_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='custom_purpose',
        ),
        migrations.AddField(
            model_name='appointment',
            name='specify_purpose',
            field=models.CharField(blank=True, help_text="Specify purpose when 'Others' is selected", max_length=200, null=True, verbose_name='Please specify your purpose'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(choices=[('', '---------'), ('employment', 'Employment'), ('business_permit', 'Business Permit'), ('government_benefits', 'Government Benefits'), ('loan_application', 'Loan Application'), ('travel', 'Travel'), ('education', 'Education'), ('others', 'Others (Please Specify)')], default='', max_length=50),
        ),
    ]
